import easing.Back
import easing.Bounce
import easing.Circ
import easing.Cubic
import easing.Elastic
import easing.Expo
import easing.GoldenRatio
import easing.Linear
import easing.Quad
import easing.Quart
import easing.Quint
import easing.Sine